version: '3.6'

services:
  nifi:
    image: apache/nifi:1.16.0
    hostname: nifi
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: "admin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "AdminAdmin12"
    volumes:
      #- ./vol/nifi/conf:/opt/nifi/nifi-current/conf
      - ./vol/nifi/logs:/opt/nifi/nifi-current/logs
      - ./vol/nifi/state:/opt/nifi/nifi-current/state
      - ./vol/nifi/content:/opt/nifi/nifi-current/content_repository
      - ./vol/nifi/database:/opt/nifi/nifi-current/database_repository
      - ./vol/nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
      - ./vol/nifi/provenance:/opt/nifi/nifi-current/provenance_repository

  mysql:
    image: mysql:8.0.28-debian
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./vol/mysql:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./vol/broker/zookeeper/data:/var/lib/zookeeper/data
      - ./vol/broker/zookeeper/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.1.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./vol/broker/kafka/data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:0.3.3
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181