version: '3.6'

services:
  nifi:
    image: apache/nifi:1.16.0
    ports:
      - 8443:8443
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: "admin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "AdminAdmin12"
    volumes:
      #- ./vol/nifi/conf:/opt/nifi/nifi-current/conf
      - ./vol/nifi/logs:/opt/nifi/nifi-current/logs
      - ./vol/nifi/state:/opt/nifi/nifi-current/state
      - ./vol/nifi/content:/opt/nifi/nifi-current/content_repository
      - ./vol/nifi/database:/opt/nifi/nifi-current/database_repository
      - ./vol/nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
      - ./vol/nifi/provenance:/opt/nifi/nifi-current/provenance_repository
